// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type netioNetioVal struct {
	_       structs.HostLayout
	RxBytes uint64
	TxBytes uint64
}

// loadNetio returns the embedded CollectionSpec for netio.
func loadNetio() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetioBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load netio: %w", err)
	}

	return spec, err
}

// loadNetioObjects loads netio and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netioObjects
//	*netioPrograms
//	*netioMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetioObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetio()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netioSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netioSpecs struct {
	netioProgramSpecs
	netioMapSpecs
	netioVariableSpecs
}

// netioProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netioProgramSpecs struct {
	FentryTcpCleanupRbuf *ebpf.ProgramSpec `ebpf:"fentry_tcp_cleanup_rbuf"`
	FentryTcpSendmsg     *ebpf.ProgramSpec `ebpf:"fentry_tcp_sendmsg"`
}

// netioMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netioMapSpecs struct {
	NetioCounters *ebpf.MapSpec `ebpf:"netio_counters"`
}

// netioVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netioVariableSpecs struct {
}

// netioObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetioObjects or ebpf.CollectionSpec.LoadAndAssign.
type netioObjects struct {
	netioPrograms
	netioMaps
	netioVariables
}

func (o *netioObjects) Close() error {
	return _NetioClose(
		&o.netioPrograms,
		&o.netioMaps,
	)
}

// netioMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetioObjects or ebpf.CollectionSpec.LoadAndAssign.
type netioMaps struct {
	NetioCounters *ebpf.Map `ebpf:"netio_counters"`
}

func (m *netioMaps) Close() error {
	return _NetioClose(
		m.NetioCounters,
	)
}

// netioVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetioObjects or ebpf.CollectionSpec.LoadAndAssign.
type netioVariables struct {
}

// netioPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetioObjects or ebpf.CollectionSpec.LoadAndAssign.
type netioPrograms struct {
	FentryTcpCleanupRbuf *ebpf.Program `ebpf:"fentry_tcp_cleanup_rbuf"`
	FentryTcpSendmsg     *ebpf.Program `ebpf:"fentry_tcp_sendmsg"`
}

func (p *netioPrograms) Close() error {
	return _NetioClose(
		p.FentryTcpCleanupRbuf,
		p.FentryTcpSendmsg,
	)
}

func _NetioClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netio_bpfel.o
var _NetioBytes []byte
